<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
// use Illuminate\Foundation\Auth\Usuarios as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class Usuarios extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

     /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'ID_USUARIO',
        'NOMBRE',
        'USUARIO',
        'CLAVE',
        'ADMINISTRADOR',
        'ACCESO',
        'CATALOGO_PERSONAL',
        'CATALOGO_CLIENTES',
        'CATALOGO_EQUIPO',
        'CATALOGO_PROVEEDORES',
        'CATALOGO_COMPANIAS',
        'CATALOGO_TIPOSMOVS',
        'CATALOGO_NOTAS',
        'CATALOGO_USUARIOS',
        'VENTAS_ACCESO',
        'VENTAS_NUEVA',
        'VENTAS_EDITAR',
        'VENTAS_DOCS',
        'VENTAS_STATUS',
        'VENTAS_DUPLICAR',
        'VENTAS_IMPRIMIR',
        'VENTAS_CANCELAR',
        'VENTAS_REPORTES',
        'PROYECTOS_ACCESO',
        'PROYECTOS_NUEVO',
        'PROYECTOS_EDITAR',
        'PROYECTOS_CANCELAR',
        'PROYECTOS_PERSONAL',
        'PROYECTOS_PERSONAL_AGREGAR',
        'PROYECTOS_PERSONAL_BORRAR',
        'PROYECTOS_EQUIPOS',
        'PROYECTOS_SEGUIMIENTOS',
        'PROYECTOS_SEGUIMIENTOS_AGREGAR',
        'PROYECTOS_SEGUIMIENTOS_DETALLE',
        'PROYECTOS_SEGUIMIENTOS_AVANCE',
        'PROYECTOS_IMPRIMIR',
        'PROYECTOS_DOCS',
        'PROYECTOS_REPORTES',
        'PROYECTOS_CARTA',
        'PROYECTOS_QUEJAS',
        'COMPRAS_ACCESO',
        'COMPRAS_REQ',
        'COMPRAS_REQ_NUEVA',
        'COMPRAS_REQ_EDITAR',
        'COMPRAS_REQ_CANCELAR',
        'COMPRAS_REQ_AUTORIZAR',
        'COMPRAS_REQ_DETALLE',
        'COMPRAS_REQ_IMPRIMIR',
        'COMPRAS_LISTA',
        'COMPRAS_AUTORIZAR',
        'COMPRAS_EDITAR',
        'COMPRAS_CANCELAR',
        'COMPRAS_DETALLE',
        'COMPRAS_COTIZACION',
        'COMPRAS_IMPRIMIR',
        'COMPRAS_CERR',
        'COMPRAS_CERR_STATUS',
        'COMPRAS_CERR_IMPRIMIR',
        'COMPRAS_CERR_DETALLE',
        'COMPRAS_CANCEL',
        'COMPRAS_CANCEL_IMPRIMIR',
        'COMPRAS_CANCEL_DETALLE',
        'FACTURACION',
        'GENERAL_CAMBIARCLAVE',
        'GENERAL_OPCIONES',
        'FACTURACION_PORFACTURAR',
        'FACTURACION_PARTIDAS',
        'FACTURACION_FACTURAS',
        'FACTURACION_NUEVA',
        'FACTURACION_EDITAR',
        'FACTURACION_CANCELAR',
        'FACTURACION_IMPRIMIR',
        'FACTURACION_REPORTES',
        'CUENTAS',
        'HISTORICO',
        'ALMACEN',
        'TODAS_COTIZACIONES',
        'FACTURACION_TOTALES',
        'HISTORICO_STATUS',
        'FACTURAS_PAGADO',
        'CATALOGO_PERSONAL_AGREGAR',
        'CATALOGO_PERSONAL_EDITAR',
        'CATALOGO_PERSONAL_BORRAR',
        'CATALOGO_CLIENTES_AGREGAR',
        'CATALOGO_CLIENTES_EDITAR',
        'CATALOGO_CLIENTES_BORRAR',
        'CATALOGO_EQUIPO_AGREGAR',
        'CATALOGO_EQUIPO_EDITAR',
        'CATALOGO_EQUIPO_BORRAR',
        'CATALOGO_PROVEEDORES_AGREGAR',
        'CATALOGO_PROVEEDORES_EDITAR',
        'CATALOGO_PROVEEDORES_BORRAR',
        'CATALOGO_COMPANIAS_AGREGAR',
        'CATALOGO_COMPANIAS_EDITAR',
        'CATALOGO_COMPANIAS_BORRAR',
        'CATALOGO_TIPOSMOVS_AGREGAR',
        'CATALOGO_TIPOSMOVS_EDITAR',
        'CATALOGO_TIPOSMOVS_BORRAR',
        'CATALOGO_NOTAS_AGREGAR',
        'CATALOGO_NOTAS_EDITAR',
        'CATALOGO_NOTAS_BORRAR',
        'CATALOGO_USUARIOS_AGREGAR',
        'CATALOGO_USUARIOS_EDITAR',
        'CATALOGO_USUARIOS_BORRAR',
        'CATALOGO_USUARIOS_PERMISOS',
        'CATALOGO_PLANTAS_AGREGAR',
        'CATALOGO_PLANTAS_EDITAR',
        'CATALOGO_PLANTAS_BORRAR',
        'CATALOGO_IDENTIFICADORES',
        'CATALOGO_ID_AGREGAR',
        'CATALOGO_ID_EDITAR',
        'CATALOGO_ID_BORRAR',
        'CATALOGO_UNIDADES',
        'CATALOGO_UNIDADES_AGREGAR',
        'CATALOGO_UNIDADES_EDITAR',
        'CATALOGO_UNIDADES_BORRAR',
        'ID_EMPLEADO',
        'PROYECTOS_SEGUIMIENTOS_PERSONAL',
        'ALMACEN_ENTRADA',
        'ALMACEN_EDITAR',
        'PROYECTOS_ELIMINAR',
        'TODOS_PROYECTOS',
        'SALDOS_PROYECTOS',
        'CUOTA_COTIZACION',
        'PROYECTOS_VIGENTE',
        'VENTAS_BORRAR',
        'PROYECTOS_DOCUMENTOS',
        'PROYECTOS_DOCUMENTOS_CAMBIAR',
        'PROYECTOS_DOCUMENTOS_BORRAR',
        'COMPRAS_REQ_CAMBIARSOLICITA',
        'VIATICOS',
        'VIATICOS_NUEVO',
        'VIATICOS_EDITAR',
        'VIATICOS_ELIMINAR',
        'VIATICOS_CANCELAR',
        'VIATICOS_AUTORIZAR',
        'CUENTA',
        'CUENTABANCO',
        'VIATICOS_CONTROL',
        'VIATICOS_SOBREGIRAR',
        'VIATICOS_DOCUMENTOS',
        'DEPARTAMENTO',
        'CATALOGO_TIPOCAMBIO',
        'CATALOGO_TIPOCAMBIO_AGREGAR',
        'CATALOGO_TIPOCAMBIO_EDITAR',
        'CATALOGO_TIPOCAMBIO_BORRAR',
        'VIATICOS_DEPOSITAR',
        'VIATICOS_EDITARAUTORIZADO',
        'CATALOGO_MATERIALES',
        'Nombre31',
        'CuentaBanco31',
        'Banco31',
        'TipoViatico',
        'Oficina',
        'Proyectos_VerPartidas',
        'Compras_EliminarRequisiciones',
        'Compras_Prioridad',
        'Minutas',
        'Ver_Solo_Ciudad',
        'Minuta_Editar',
        'Minuta_Ver',
        'Minuta_Notas',
        'Minuta_Archivos',
        'COMPRAS_CERRAR',
        'Minuta_Requiere',
        'PROYECTOS_BITÁCORA',
        'PROYECTOS_NIVEL',
        'VIATICOS_CAPTURARGASTOS',
        'VIATICOS_REPORTES',
        'Status',
        'Movil',
        'MOVIL_COMPRAS',
        'MOVIL_BIRACORA',
        'AplicaA',
        'AplicaA_Agregar',
        'AplicaA_Editar',
        'Oficinas',
        'Oficinas_Agregar',
        'Oficinas_Editar',
        'Areas',
        'Areas_Agregar',
        'Areas_Editar',

        'eamil',
        'password'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}
